name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install additional packages
        run: |
          set -ex
          apt-get -qy update
          apt-get -qy install ghostscript zip
      - name: Install the Fithesis package
        run: |
          set -ex
          make base
          make install-base to="$HOME"/texmf nohash=true
      - name: Typeset documentation, user guides, and user examples
        run: |
          set -ex
          make dist
      - name: Upload artifact fithesis.tds.zip
        uses: actions/upload-artifact@v2
        with:
          name: fithesis.tds.zip
          path: fithesis.tds.zip
      - name: Upload artifact fithesis.ctan.zip
        uses: actions/upload-artifact@v2
        with:
          name: fithesis.ctan.zip
          path: fithesis.ctan.zip
      - name: Upload artifact fithesis.zip
        uses: actions/upload-artifact@v2
        with:
          name: fithesis.zip
          path: fithesis.zip
